using System.ComponentModel;
using AutoWork.Core.Configuration;

namespace AutoWork.Desktop.Localization;

/// <summary>
/// Interface text in English and Bahasa Indonesia.
///
/// Kept as a keyed table rather than generated resources so both languages sit side by side in
/// one file — when a label changes, the translation is right there and cannot silently drift.
/// Views bind through the indexer, and switching language raises a change for every key at once.
/// </summary>
public sealed class Strings : INotifyPropertyChanged
{
    private UiLanguage _language = UiLanguage.System;

    public event PropertyChangedEventHandler? PropertyChanged;

    public UiLanguage Language
    {
        get => _language;
        set
        {
            if (_language == value) return;
            _language = value;

            // "Item[]" is the conventional name for "every indexer value changed", which is
            // what tells every {Binding L[...]} in the tree to re-read.
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Language)));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsIndonesian)));
        }
    }

    public bool IsIndonesian => Resolve() == UiLanguage.Indonesian;

    public string this[string key] =>
        (Resolve() == UiLanguage.Indonesian ? Indonesian : English).GetValueOrDefault(key)
        ?? English.GetValueOrDefault(key)
        ?? key;

    private UiLanguage Resolve()
    {
        if (_language != UiLanguage.System) return _language;

        // "System" follows the OS, and anything that is not Indonesian falls back to English.
        var culture = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return string.Equals(culture, "id", StringComparison.OrdinalIgnoreCase)
            ? UiLanguage.Indonesian
            : UiLanguage.English;
    }

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["app.tagline"] = "Your digital coworker",
        ["app.credit"] = "Built by Gravicode Studios · led by Kang Fadhil",

        ["nav.work"] = "Work",
        ["nav.jobs"] = "Jobs",
        ["nav.history"] = "History",
        ["nav.recycle"] = "Recycle",
        ["nav.activity"] = "Activity",
        ["nav.knowledge"] = "Knowledge",
        ["nav.skills"] = "Skills",
        ["nav.mcp"] = "MCP",
        ["nav.integrations"] = "Integrations",
        ["nav.settings"] = "Settings",

        ["organ.think"] = "Think",
        ["organ.see"] = "See",
        ["organ.act"] = "Act",

        ["work.prompt"] = "What should I take care of?",
        ["work.placeholder"] = "Organise everything in my Downloads folder by type, then list what moved.",
        ["work.start"] = "Start work",
        ["work.stop"] = "Stop",
        ["work.clear"] = "Clear",
        ["work.tape"] = "WORK TAPE",
        ["work.plan"] = "PLAN",
        ["work.idle"] = "Nothing running.",
        ["work.idle.hint"] = "Describe a job above and AutoWork will plan it, do it, and check its own work.",
        ["work.summary"] = "RESULT",
        ["work.model"] = "Model",
        ["work.elapsed"] = "Elapsed",
        ["work.steps"] = "Steps",
        ["work.compacted"] = "Context compacted",
        ["work.tokens"] = "Tokens",
        ["work.tokens.atleast"] = "at least {0:N0}",
        ["work.cost"] = "Cost",
        ["work.verified"] = "Verified",
        ["work.unverified"] = "Not verified",

        ["work.pause"] = "Pause",
        ["work.resume"] = "Resume",
        ["work.paused"] = "Paused — it will pick up where it left off.",
        ["work.paused.before"] = "Holding before step {0}",
        ["work.corrected"] = "You corrected it",
        ["work.pausing"] = "Pausing after this step…",
        ["work.steer"] = "Anything to change?",
        ["work.steer.send"] = "Send correction",
        ["work.steer.hint"] = "Type a correction and it goes in before the next step. Leave it empty to just carry on.",
        ["work.steer.queued"] = "Your correction goes in before the next step.",

        ["history.title"] = "Past runs",
        ["history.subtitle"] = "Every run is kept so you can see what it did and set it going again.",
        ["history.empty"] = "No runs yet.",
        ["history.empty.hint"] = "Once you start a job, it will be recorded here.",
        ["history.open"] = "Open",
        ["history.rerun"] = "Run it again",
        ["history.delete"] = "Delete",
        ["history.refresh"] = "Refresh",
        ["history.off"] = "Run history is turned off in Settings, so nothing new is being recorded.",
        ["history.viewing"] = "You are looking at a past run.",
        ["history.close"] = "Back to work",
        ["history.tools"] = "Tool calls",
        ["history.status.succeeded"] = "Succeeded",
        ["history.status.failed"] = "Failed",
        ["history.status.cancelled"] = "Stopped",

        ["approval.changes"] = "WHAT WOULD CHANGE",

        ["perm.browser"] = "Let AutoWork use a browser you are signed in to",
        ["perm.browser.hint"] = "Opens a real browser with its own profile that stays signed in, so AutoWork can work pages that need a login. It acts as you on those sites, and asks before every navigation and click.",
        ["browser.path"] = "Browser to use (leave empty to find Edge or Chrome)",
        ["browser.found"] = "Will use: {0}",
        ["browser.notfound"] = "No browser found. Install Edge or Chrome, or give the full path.",
        ["browser.headless"] = "Run it hidden",

        ["mcp.community"] = "community",
        ["mcp.sources"] = "MORE SERVERS",
        ["mcp.sources.hint"] = "This list is a starting point. These collections have hundreds more — copy the command from the vendor's page and add it by hand.",
        ["mcp.manual.open"] = "Add by hand",
        ["mcp.manual.title"] = "ADD A SERVER YOURSELF",
        ["mcp.manual.hint"] = "Paste what the vendor's page tells you to run. Most MCP servers are not in any catalogue, and Unity and Unreal Engine only work this way.",
        ["mcp.manual.name"] = "Name it",
        ["mcp.manual.stdio"] = "A command",
        ["mcp.manual.http"] = "A URL",
        ["mcp.manual.command"] = "Command, e.g. npx or uvx",
        ["mcp.manual.args"] = "Arguments, e.g. -y some-mcp-server",
        ["mcp.manual.url"] = "https://example.com/mcp",
        ["mcp.manual.env"] = "Environment variables, one NAME=value per line. Tokens are kept in the secret store.",
        ["mcp.manual.save"] = "Add it",
        ["mcp.manual.needname"] = "Give it a name so you can tell it apart later.",
        ["mcp.manual.needcommand"] = "A command server needs a command to run.",
        ["mcp.manual.needurl"] = "That is not a valid URL.",
        ["mcp.manual.added.note"] = "Added by hand.",

        ["speech.title"] = "MEETINGS AND RECORDINGS",
        ["speech.subtitle"] = "Turn a recording into text, then have AutoWork pull out the decisions and who owes what. AutoWork ships no speech model — point this at one you already have.",
        ["speech.off"] = "Off",
        ["speech.local"] = "Use a speech model on this computer",
        ["speech.remote"] = "Send recordings to a service",
        ["speech.command"] = "Command to run, e.g. whisper-cli",
        ["speech.arguments"] = "Arguments — {audio} and {model} are filled in",
        ["speech.model"] = "Model file",
        ["speech.local.hint"] = "Nothing leaves this computer. whisper.cpp, faster-whisper and openai-whisper all work; each wants its own arguments.",
        ["speech.remote.warning"] = "This uploads the recording, including everyone in it. Only choose it if that is acceptable for these meetings.",
        ["speech.endpoint"] = "Endpoint, e.g. https://api.openai.com/v1",
        ["speech.remotemodel"] = "Model, e.g. whisper-1",

        ["jobs.title"] = "Saved jobs",
        ["jobs.subtitle"] = "Work you want done again — on a schedule, or whenever a folder changes. A job runs in the Work view exactly as if you had typed it, and asks for the same permissions.",
        ["jobs.add"] = "New job",
        ["jobs.empty"] = "No saved jobs.",
        ["jobs.empty.hint"] = "Add one for anything you find yourself asking for regularly.",
        ["jobs.enabled"] = "On",
        ["jobs.name"] = "Name it (optional)",
        ["jobs.goal"] = "What should it do? Write it exactly as you would in the Work view.",
        ["jobs.apply"] = "Save",
        ["jobs.runnow"] = "Run now",
        ["jobs.saved"] = "Saved \"{0}\".",
        ["jobs.trigger.manual"] = "Only when I say",
        ["jobs.trigger.schedule"] = "On a schedule",
        ["jobs.trigger.folder"] = "When a folder changes",
        ["jobs.period.hourly"] = "Every hour",
        ["jobs.period.daily"] = "Every day",
        ["jobs.period.weekly"] = "Every week",
        ["jobs.folder"] = "Folder to watch",
        ["jobs.filter"] = "*.pdf",
        ["jobs.subfolders"] = "Include subfolders",
        ["jobs.quiet"] = "Wait for quiet (seconds)",
        ["jobs.next"] = "Next: {0}",
        ["jobs.reason.manual"] = "you asked for it",

        ["work.job.running"] = "Started by your saved job \"{0}\" — {1}.",
        ["work.job.finished"] = "finished",

        ["recycle.title"] = "Deleted files",
        ["recycle.subtitle"] = "Anything AutoWork deleted is kept here until you say otherwise. Put it back where it was, or clear it out.",
        ["recycle.refresh"] = "Refresh",
        ["recycle.open"] = "Open folder",
        ["recycle.empty"] = "Empty it",
        ["recycle.empty.none"] = "Nothing here.",
        ["recycle.empty.hint"] = "Files AutoWork deletes are moved here first, so they can be put back.",
        ["recycle.restore"] = "Put it back",
        ["recycle.restore.over"] = "Replace what's there",
        ["recycle.purge"] = "Delete for good",
        ["recycle.purge.failed"] = "It could not be deleted — it may be open in another program.",
        ["recycle.emptied"] = "Cleared {0} item(s).",
        ["recycle.origin.unknown"] = "Deleted before AutoWork recorded where files came from, so it cannot be put back automatically.",
        ["recycle.softdelete.off"] = "Soft delete is off in Settings, so new deletions are permanent and will not appear here.",
        ["work.nomodel"] = "No model is configured yet. Open Settings › Models to add one.",
        ["work.examples"] = "TRY SOMETHING LIKE",

        ["approval.title"] = "AutoWork needs your permission",
        ["approval.allow"] = "Allow once",
        ["approval.allowrun"] = "Allow for this run",
        ["approval.deny"] = "Deny",
        ["approval.affected"] = "Affects",

        ["activity.title"] = "Activity",
        ["activity.subtitle"] = "Every action AutoWork has taken on this computer.",
        ["activity.empty"] = "No actions recorded yet.",
        ["activity.refresh"] = "Refresh",
        ["activity.open"] = "Open log folder",

        ["knowledge.title"] = "Knowledge",
        ["knowledge.subtitle"] = "Notes AutoWork keeps between sessions.",
        ["knowledge.new"] = "New knowledge base",
        ["knowledge.empty"] = "No knowledge bases yet.",
        ["knowledge.empty.hint"] = "Create one, and AutoWork will remember what it learns about your work.",
        ["knowledge.entries"] = "notes",
        ["knowledge.delete"] = "Delete",
        ["knowledge.autoattach"] = "Use automatically",
        ["knowledge.name"] = "Name",
        ["knowledge.add"] = "Add note",
        ["knowledge.addfile"] = "Add from file",
        ["knowledge.addfile.hint"] = "Word, PowerPoint, Excel, PDF, CSV, HTML, text or Markdown. The file name becomes the title.",
        ["knowledge.imported"] = "Imported {0} file(s).",
        ["knowledge.entry.title"] = "Title",
        ["knowledge.entry.text"] = "What to remember",

        ["skills.title"] = "Skills",
        ["skills.subtitle"] = "Instructions the agent can follow for particular kinds of work. It reads a skill only when the job calls for it.",
        ["skills.installed"] = "INSTALLED",
        ["skills.installed.empty"] = "No skills installed. Browse a repository below and add what fits your work.",
        ["skills.installed.badge"] = "Installed",
        ["skills.repos"] = "REPOSITORIES",
        ["skills.repos.hint"] = "Skills are read from these GitHub repositories. Add your own — a company's internal skills repository works the same way.",
        ["skills.repo.invalid"] = "Enter a repository as owner/name, or paste its GitHub URL.",
        ["skills.search"] = "Filter by name or description",
        ["skills.browse"] = "Browse",
        ["skills.browsing"] = "Reading repositories…",
        ["skills.install"] = "Add",
        ["skills.found"] = "Found {0} skills across {1} repositories.",
        ["skills.none"] = "No skills found. Check the repository names and your network.",
        ["skills.installed.msg"] = "Installed {0} with {1} bundled file(s).",
        ["skills.failed"] = "Could not download {0}.",
        ["skills.removed"] = "Removed {0}.",

        ["mcp.title"] = "MCP servers",
        ["mcp.subtitle"] = "Model Context Protocol servers lend the agent their own tools — a browser, a database, a vendor's API. Add one, test it, then enable it.",
        ["mcp.disabled"] = "MCP is turned off. A server is a program AutoWork starts with your full rights, so it needs an explicit switch: Settings › Permissions › Allow MCP servers.",
        ["mcp.search"] = "Search the catalogue",
        ["mcp.add"] = "Add",
        ["mcp.added.badge"] = "Added",
        ["mcp.added"] = "Added {0}. Enable it on the right when you are ready.",
        ["mcp.removed"] = "Removed {0}.",
        ["mcp.needs"] = "{0} is required.",
        ["mcp.test"] = "Test",
        ["mcp.testing"] = "Starting the server…",
        ["mcp.yours"] = "YOUR SERVERS",
        ["mcp.yours.empty"] = "Nothing added yet. Pick one from the catalogue.",

        ["integrations.title"] = "Integrations",
        ["integrations.subtitle"] = "Connect the services you already work in.",
        ["integrations.enable"] = "Enabled",
        ["integrations.test"] = "Test connection",
        ["integrations.save"] = "Save",
        ["integrations.docs"] = "Get credentials",

        ["settings.title"] = "Settings",
        ["settings.models"] = "Models",
        ["settings.permissions"] = "Permissions",
        ["settings.agent"] = "Agent",
        ["settings.appearance"] = "Appearance",
        ["settings.about"] = "About",

        ["models.subtitle"] = "AutoWork works with any provider you configure. Keys stay on this computer.",
        ["models.add"] = "Add model",
        ["models.empty"] = "No models configured.",
        ["models.test"] = "Test",
        ["models.remove"] = "Remove",
        ["models.provider"] = "Provider",
        ["models.name"] = "Display name",
        ["models.endpoint"] = "Endpoint",
        ["models.modelid"] = "Model id",
        ["models.apikey"] = "API key",
        ["models.apikey.hint"] = "Stored encrypted on this computer. Type env:NAME to read an environment variable instead.",
        ["models.context"] = "Context window (tokens)",
        ["models.roles"] = "ROLES",
        ["models.role.planner"] = "Planning and reasoning",
        ["models.role.executor"] = "Doing the work",
        ["models.role.vision"] = "Reading the screen",
        ["models.role.embedding"] = "Knowledge search",
        ["models.capabilities"] = "Capabilities",
        ["models.cap.tools"] = "Tools",
        ["models.cap.vision"] = "Vision",
        ["models.cap.embeddings"] = "Embeddings",
        ["models.cap.reasoning"] = "Reasoning",

        ["perm.subtitle"] = "AutoWork can only reach the folders you grant here. Nothing else on this computer is visible to it.",
        ["perm.folders"] = "FOLDERS",
        ["perm.add"] = "Add folder",
        ["perm.none"] = "No folders granted. AutoWork cannot read or write anything yet.",
        ["perm.readonly"] = "Read only",
        ["perm.readwrite"] = "Read and write",
        ["perm.remove"] = "Remove",
        ["perm.capabilities"] = "CAPABILITIES",
        ["perm.delete"] = "Allow deleting files",
        ["perm.softdelete"] = "Move deleted files to a recycle folder instead of erasing them",
        ["perm.shell"] = "Allow running shell commands",
        ["perm.shellapproval"] = "Ask before every command",
        ["perm.screen"] = "Allow screen capture",
        ["perm.input"] = "Allow controlling mouse and keyboard",
        ["perm.inputapproval"] = "Ask before every input action",
        ["perm.skillscripts"] = "Allow running scripts bundled with skills",
        ["perm.skillscripts.approval"] = "Ask before every script",
        ["perm.skillscripts.hint"] = "Skills can ship scripts. Running one runs code from a repository with your full rights, so this is separate from the shell switch.",
        ["perm.mcp"] = "Allow MCP servers",
        ["perm.mcp.hint"] = "MCP servers are programs AutoWork starts with your full rights. PathGuard cannot see inside them. Leave this off unless you need one.",
        ["perm.network"] = "Allow network access",
        ["perm.searchkey"] = "Tavily API key for web search",
        ["perm.searchkeyhint"] = "Optional. Without one, search still works using DuckDuckGo and Wikipedia. The key is stored encrypted, never in config.json.",
        ["perm.confirm"] = "Ask before writing, deleting or running anything",

        ["agent.maxsteps"] = "Maximum steps per run",
        ["agent.subagents"] = "Split independent work across parallel sub-agents",
        ["agent.parallel"] = "Maximum parallel sub-agents",
        ["agent.verify"] = "Check my own work before reporting success",
        ["agent.compact"] = "Summarise older context automatically as the window fills",
        ["agent.threshold"] = "Compact when this full",
        ["rules.title"] = "STANDING ANSWERS",
        ["rules.subtitle"] = "Answer once instead of every time. These decide what you are asked about — they never widen what AutoWork can reach, because every action still goes through your granted folders.",
        ["rules.none"] = "No rules. You will be asked about every action.",
        ["rules.add"] = "Add a rule",
        ["rules.never"] = "Never allow",
        ["rules.always"] = "Always allow",
        ["rules.anykind"] = "Any action",
        ["rules.path"] = "Folder this applies to",
        ["rules.browse"] = "Choose…",

        ["models.pricing"] = "PRICE PER MILLION TOKENS",
        ["models.price.in"] = "Input",
        ["models.price.out"] = "Output",
        ["models.pricing.hint"] = "Optional. Copy these from your provider's pricing page and each run reports what it cost. Leave blank and it reports tokens only.",

        ["agent.localembed"] = "Search knowledge without leaving this computer",
        ["agent.localembed.hint"] = "Indexes your notes here instead of sending them to an embedding model. It matches word forms and survives typos, but it will not know that \"bill\" and \"invoice\" mean the same thing — a hosted model is better at meaning.",
        ["agent.streaming"] = "Show replies as they are written",
        ["agent.history"] = "Keep a record of each run",
        ["agent.retention"] = "Keep runs for (days)",

        ["appearance.theme"] = "Theme",
        ["appearance.theme.system"] = "Match system",
        ["appearance.theme.light"] = "Light",
        ["appearance.theme.dark"] = "Dark",
        ["appearance.language"] = "Language",
        ["appearance.language.system"] = "Match system",
        ["appearance.motion"] = "Reduce motion",

        ["about.version"] = "Version",
        ["about.datafolder"] = "Data folder",
        ["about.open"] = "Open",

        ["common.save"] = "Save",
        ["common.cancel"] = "Cancel",
        ["common.close"] = "Close",
        ["common.saved"] = "Saved.",
        ["common.testing"] = "Testing…",
    };

    private static readonly Dictionary<string, string> Indonesian = new(StringComparer.Ordinal)
    {
        ["app.tagline"] = "Rekan kerja digital Anda",
        ["app.credit"] = "Dibuat oleh Gravicode Studios · dipimpin Kang Fadhil",

        ["nav.work"] = "Kerja",
        ["nav.jobs"] = "Tugas",
        ["nav.history"] = "Riwayat",
        ["nav.recycle"] = "Pemulihan",
        ["nav.activity"] = "Aktivitas",
        ["nav.knowledge"] = "Pengetahuan",
        ["nav.skills"] = "Skill",
        ["nav.mcp"] = "MCP",
        ["nav.integrations"] = "Integrasi",
        ["nav.settings"] = "Pengaturan",

        ["organ.think"] = "Pikir",
        ["organ.see"] = "Lihat",
        ["organ.act"] = "Tindak",

        ["work.prompt"] = "Apa yang perlu saya kerjakan?",
        ["work.placeholder"] = "Rapikan folder Downloads saya berdasarkan jenis file, lalu buat daftar yang dipindahkan.",
        ["work.start"] = "Mulai kerja",
        ["work.stop"] = "Hentikan",
        ["work.clear"] = "Bersihkan",
        ["work.tape"] = "PITA KERJA",
        ["work.plan"] = "RENCANA",
        ["work.idle"] = "Tidak ada yang berjalan.",
        ["work.idle.hint"] = "Tuliskan pekerjaan di atas — AutoWork akan merencanakan, mengerjakan, lalu memeriksa hasilnya sendiri.",
        ["work.summary"] = "HASIL",
        ["work.model"] = "Model",
        ["work.elapsed"] = "Waktu",
        ["work.steps"] = "Langkah",
        ["work.compacted"] = "Konteks diringkas",
        ["work.tokens"] = "Token",
        ["work.tokens.atleast"] = "minimal {0:N0}",
        ["work.cost"] = "Biaya",
        ["work.verified"] = "Terverifikasi",
        ["work.unverified"] = "Belum terverifikasi",

        ["work.pause"] = "Jeda",
        ["work.resume"] = "Lanjutkan",
        ["work.paused"] = "Dijeda — nanti dilanjutkan dari tempat terakhir.",
        ["work.paused.before"] = "Berhenti sebelum langkah {0}",
        ["work.corrected"] = "Anda mengoreksinya",
        ["work.pausing"] = "Menjeda setelah langkah ini…",
        ["work.steer"] = "Ada yang perlu diubah?",
        ["work.steer.send"] = "Kirim koreksi",
        ["work.steer.hint"] = "Tulis koreksinya, akan disisipkan sebelum langkah berikutnya. Kosongkan saja kalau tinggal dilanjutkan.",
        ["work.steer.queued"] = "Koreksi Anda disisipkan sebelum langkah berikutnya.",

        ["history.title"] = "Riwayat kerja",
        ["history.subtitle"] = "Setiap run disimpan supaya Anda bisa melihat apa yang dikerjakan dan menjalankannya lagi.",
        ["history.empty"] = "Belum ada run.",
        ["history.empty.hint"] = "Begitu Anda mulai bekerja, hasilnya tercatat di sini.",
        ["history.open"] = "Buka",
        ["history.rerun"] = "Jalankan lagi",
        ["history.delete"] = "Hapus",
        ["history.refresh"] = "Muat ulang",
        ["history.off"] = "Riwayat run dimatikan di Pengaturan, jadi tidak ada yang dicatat.",
        ["history.viewing"] = "Anda sedang melihat run yang sudah lewat.",
        ["history.close"] = "Kembali bekerja",
        ["history.tools"] = "Panggilan tool",
        ["history.status.succeeded"] = "Berhasil",
        ["history.status.failed"] = "Gagal",
        ["history.status.cancelled"] = "Dihentikan",

        ["approval.changes"] = "YANG AKAN BERUBAH",

        ["perm.browser"] = "Izinkan AutoWork memakai peramban tempat Anda sudah masuk",
        ["perm.browser.hint"] = "Membuka peramban sungguhan dengan profil tersendiri yang tetap masuk, sehingga AutoWork bisa mengerjakan halaman yang butuh login. Ia bertindak sebagai Anda di situs itu, dan bertanya sebelum setiap navigasi dan klik.",
        ["browser.path"] = "Peramban yang dipakai (kosongkan untuk mencari Edge atau Chrome)",
        ["browser.found"] = "Akan memakai: {0}",
        ["browser.notfound"] = "Tidak ada peramban ditemukan. Pasang Edge atau Chrome, atau isi path lengkapnya.",
        ["browser.headless"] = "Jalankan tersembunyi",

        ["mcp.community"] = "komunitas",
        ["mcp.sources"] = "SERVER LAINNYA",
        ["mcp.sources.hint"] = "Daftar ini hanya titik awal. Koleksi berikut memuat ratusan lainnya — salin perintahnya dari halaman vendor lalu tambahkan secara manual.",
        ["mcp.manual.open"] = "Tambah manual",
        ["mcp.manual.title"] = "TAMBAHKAN SERVER SENDIRI",
        ["mcp.manual.hint"] = "Tempelkan apa yang disebutkan halaman vendor. Sebagian besar server MCP tidak ada di katalog mana pun, dan Unity serta Unreal Engine hanya bisa lewat cara ini.",
        ["mcp.manual.name"] = "Beri nama",
        ["mcp.manual.stdio"] = "Sebuah perintah",
        ["mcp.manual.http"] = "Sebuah URL",
        ["mcp.manual.command"] = "Perintah, mis. npx atau uvx",
        ["mcp.manual.args"] = "Argumen, mis. -y some-mcp-server",
        ["mcp.manual.url"] = "https://example.com/mcp",
        ["mcp.manual.env"] = "Environment variable, satu NAME=value per baris. Token disimpan di secret store.",
        ["mcp.manual.save"] = "Tambahkan",
        ["mcp.manual.needname"] = "Beri nama agar nanti mudah dibedakan.",
        ["mcp.manual.needcommand"] = "Server berbasis perintah butuh perintah yang dijalankan.",
        ["mcp.manual.needurl"] = "URL itu tidak valid.",
        ["mcp.manual.added.note"] = "Ditambahkan manual.",

        ["speech.title"] = "RAPAT DAN REKAMAN",
        ["speech.subtitle"] = "Ubah rekaman jadi teks, lalu minta AutoWork menarik keputusan dan siapa bertanggung jawab atas apa. AutoWork tidak membawa model suara — arahkan ke model yang sudah Anda punya.",
        ["speech.off"] = "Mati",
        ["speech.local"] = "Pakai model suara di komputer ini",
        ["speech.remote"] = "Kirim rekaman ke layanan",
        ["speech.command"] = "Perintah yang dijalankan, mis. whisper-cli",
        ["speech.arguments"] = "Argumen — {audio} dan {model} akan diisi",
        ["speech.model"] = "Berkas model",
        ["speech.local.hint"] = "Tidak ada yang keluar dari komputer ini. whisper.cpp, faster-whisper, dan openai-whisper sama-sama bisa; masing-masing punya argumennya sendiri.",
        ["speech.remote.warning"] = "Ini mengunggah rekaman, termasuk semua orang di dalamnya. Pilih hanya kalau itu memang dapat diterima untuk rapat-rapat ini.",
        ["speech.endpoint"] = "Endpoint, mis. https://api.openai.com/v1",
        ["speech.remotemodel"] = "Model, mis. whisper-1",

        ["jobs.title"] = "Tugas tersimpan",
        ["jobs.subtitle"] = "Pekerjaan yang ingin Anda ulang — terjadwal, atau setiap kali sebuah folder berubah. Tugas dijalankan di halaman Kerja persis seperti Anda mengetiknya sendiri, dan meminta izin yang sama.",
        ["jobs.add"] = "Tugas baru",
        ["jobs.empty"] = "Belum ada tugas tersimpan.",
        ["jobs.empty.hint"] = "Tambahkan untuk apa pun yang sering Anda minta.",
        ["jobs.enabled"] = "Aktif",
        ["jobs.name"] = "Beri nama (opsional)",
        ["jobs.goal"] = "Apa yang harus dikerjakan? Tulis persis seperti di halaman Kerja.",
        ["jobs.apply"] = "Simpan",
        ["jobs.runnow"] = "Jalankan sekarang",
        ["jobs.saved"] = "\"{0}\" disimpan.",
        ["jobs.trigger.manual"] = "Hanya kalau saya minta",
        ["jobs.trigger.schedule"] = "Terjadwal",
        ["jobs.trigger.folder"] = "Saat folder berubah",
        ["jobs.period.hourly"] = "Tiap jam",
        ["jobs.period.daily"] = "Tiap hari",
        ["jobs.period.weekly"] = "Tiap minggu",
        ["jobs.folder"] = "Folder yang dipantau",
        ["jobs.filter"] = "*.pdf",
        ["jobs.subfolders"] = "Termasuk subfolder",
        ["jobs.quiet"] = "Tunggu sampai tenang (detik)",
        ["jobs.next"] = "Berikutnya: {0}",
        ["jobs.reason.manual"] = "Anda memintanya",

        ["work.job.running"] = "Dimulai oleh tugas tersimpan \"{0}\" — {1}.",
        ["work.job.finished"] = "selesai",

        ["recycle.title"] = "Berkas terhapus",
        ["recycle.subtitle"] = "Apa pun yang dihapus AutoWork disimpan di sini sampai Anda memutuskan lain. Kembalikan ke tempat asalnya, atau bersihkan.",
        ["recycle.refresh"] = "Muat ulang",
        ["recycle.open"] = "Buka folder",
        ["recycle.empty"] = "Kosongkan",
        ["recycle.empty.none"] = "Tidak ada apa-apa di sini.",
        ["recycle.empty.hint"] = "Berkas yang dihapus AutoWork dipindahkan ke sini dulu, supaya bisa dikembalikan.",
        ["recycle.restore"] = "Kembalikan",
        ["recycle.restore.over"] = "Timpa yang ada",
        ["recycle.purge"] = "Hapus permanen",
        ["recycle.purge.failed"] = "Tidak bisa dihapus — mungkin sedang dibuka program lain.",
        ["recycle.emptied"] = "{0} item dibersihkan.",
        ["recycle.origin.unknown"] = "Dihapus sebelum AutoWork mencatat asal berkas, jadi tidak bisa dikembalikan otomatis.",
        ["recycle.softdelete.off"] = "Hapus lunak dimatikan di Pengaturan, jadi penghapusan baru bersifat permanen dan tidak muncul di sini.",
        ["work.nomodel"] = "Belum ada model yang dikonfigurasi. Buka Pengaturan › Model untuk menambahkan.",
        ["work.examples"] = "COBA SESUATU SEPERTI",

        ["approval.title"] = "AutoWork memerlukan izin Anda",
        ["approval.allow"] = "Izinkan sekali",
        ["approval.allowrun"] = "Izinkan selama sesi ini",
        ["approval.deny"] = "Tolak",
        ["approval.affected"] = "Berdampak pada",

        ["activity.title"] = "Aktivitas",
        ["activity.subtitle"] = "Semua tindakan yang dilakukan AutoWork di komputer ini.",
        ["activity.empty"] = "Belum ada tindakan tercatat.",
        ["activity.refresh"] = "Muat ulang",
        ["activity.open"] = "Buka folder log",

        ["knowledge.title"] = "Pengetahuan",
        ["knowledge.subtitle"] = "Catatan yang disimpan AutoWork antar sesi.",
        ["knowledge.new"] = "Basis pengetahuan baru",
        ["knowledge.empty"] = "Belum ada basis pengetahuan.",
        ["knowledge.empty.hint"] = "Buat satu, dan AutoWork akan mengingat apa yang dipelajarinya tentang pekerjaan Anda.",
        ["knowledge.entries"] = "catatan",
        ["knowledge.delete"] = "Hapus",
        ["knowledge.autoattach"] = "Gunakan otomatis",
        ["knowledge.name"] = "Nama",
        ["knowledge.add"] = "Tambah catatan",
        ["knowledge.addfile"] = "Tambah dari file",
        ["knowledge.addfile.hint"] = "Word, PowerPoint, Excel, PDF, CSV, HTML, teks, atau Markdown. Nama file dipakai sebagai judul.",
        ["knowledge.imported"] = "{0} file diimpor.",
        ["knowledge.entry.title"] = "Judul",
        ["knowledge.entry.text"] = "Yang perlu diingat",

        ["skills.title"] = "Skill",
        ["skills.subtitle"] = "Instruksi yang bisa diikuti agen untuk jenis pekerjaan tertentu. Skill hanya dibaca saat pekerjaannya memang membutuhkan.",
        ["skills.installed"] = "TERPASANG",
        ["skills.installed.empty"] = "Belum ada skill terpasang. Telusuri repositori di bawah lalu tambahkan yang sesuai pekerjaan Anda.",
        ["skills.installed.badge"] = "Terpasang",
        ["skills.repos"] = "REPOSITORI",
        ["skills.repos.hint"] = "Skill dibaca dari repositori GitHub berikut. Tambahkan milik Anda sendiri — repositori skill internal perusahaan bekerja dengan cara yang sama.",
        ["skills.repo.invalid"] = "Isi repositori sebagai owner/nama, atau tempel URL GitHub-nya.",
        ["skills.search"] = "Saring berdasarkan nama atau deskripsi",
        ["skills.browse"] = "Telusuri",
        ["skills.browsing"] = "Membaca repositori…",
        ["skills.install"] = "Tambah",
        ["skills.found"] = "Ditemukan {0} skill dari {1} repositori.",
        ["skills.none"] = "Tidak ada skill ditemukan. Periksa nama repositori dan jaringan Anda.",
        ["skills.installed.msg"] = "{0} dipasang beserta {1} berkas bundel.",
        ["skills.failed"] = "Gagal mengunduh {0}.",
        ["skills.removed"] = "{0} dihapus.",

        ["mcp.title"] = "Server MCP",
        ["mcp.subtitle"] = "Server Model Context Protocol meminjamkan tool miliknya ke agen — peramban, basis data, API vendor. Tambahkan, uji, lalu aktifkan.",
        ["mcp.disabled"] = "MCP sedang mati. Server adalah program yang dijalankan AutoWork dengan hak akses penuh Anda, jadi perlu sakelar eksplisit: Pengaturan › Izin › Izinkan server MCP.",
        ["mcp.search"] = "Cari di katalog",
        ["mcp.add"] = "Tambah",
        ["mcp.added.badge"] = "Ditambahkan",
        ["mcp.added"] = "{0} ditambahkan. Aktifkan di panel kanan bila sudah siap.",
        ["mcp.removed"] = "{0} dihapus.",
        ["mcp.needs"] = "{0} wajib diisi.",
        ["mcp.test"] = "Uji",
        ["mcp.testing"] = "Menjalankan server…",
        ["mcp.yours"] = "SERVER ANDA",
        ["mcp.yours.empty"] = "Belum ada yang ditambahkan. Pilih satu dari katalog.",

        ["integrations.title"] = "Integrasi",
        ["integrations.subtitle"] = "Hubungkan layanan yang sudah Anda pakai sehari-hari.",
        ["integrations.enable"] = "Aktif",
        ["integrations.test"] = "Uji koneksi",
        ["integrations.save"] = "Simpan",
        ["integrations.docs"] = "Dapatkan kredensial",

        ["settings.title"] = "Pengaturan",
        ["settings.models"] = "Model",
        ["settings.permissions"] = "Izin",
        ["settings.agent"] = "Agen",
        ["settings.appearance"] = "Tampilan",
        ["settings.about"] = "Tentang",

        ["models.subtitle"] = "AutoWork bekerja dengan penyedia mana pun yang Anda atur. Kunci API tetap di komputer ini.",
        ["models.add"] = "Tambah model",
        ["models.empty"] = "Belum ada model.",
        ["models.test"] = "Uji",
        ["models.remove"] = "Hapus",
        ["models.provider"] = "Penyedia",
        ["models.name"] = "Nama tampilan",
        ["models.endpoint"] = "Endpoint",
        ["models.modelid"] = "ID model",
        ["models.apikey"] = "Kunci API",
        ["models.apikey.hint"] = "Disimpan terenkripsi di komputer ini. Ketik env:NAMA untuk membaca variabel lingkungan.",
        ["models.context"] = "Jendela konteks (token)",
        ["models.roles"] = "PERAN",
        ["models.role.planner"] = "Perencanaan dan penalaran",
        ["models.role.executor"] = "Mengerjakan tugas",
        ["models.role.vision"] = "Membaca layar",
        ["models.role.embedding"] = "Pencarian pengetahuan",
        ["models.capabilities"] = "Kemampuan",
        ["models.cap.tools"] = "Tools",
        ["models.cap.vision"] = "Visi",
        ["models.cap.embeddings"] = "Embedding",
        ["models.cap.reasoning"] = "Penalaran",

        ["perm.subtitle"] = "AutoWork hanya bisa menjangkau folder yang Anda izinkan di sini. Selain itu tidak terlihat olehnya.",
        ["perm.folders"] = "FOLDER",
        ["perm.add"] = "Tambah folder",
        ["perm.none"] = "Belum ada folder yang diizinkan. AutoWork belum bisa membaca atau menulis apa pun.",
        ["perm.readonly"] = "Hanya baca",
        ["perm.readwrite"] = "Baca dan tulis",
        ["perm.remove"] = "Hapus",
        ["perm.capabilities"] = "KEMAMPUAN",
        ["perm.delete"] = "Izinkan menghapus file",
        ["perm.softdelete"] = "Pindahkan file terhapus ke folder daur ulang, bukan menghapus permanen",
        ["perm.shell"] = "Izinkan menjalankan perintah shell",
        ["perm.shellapproval"] = "Tanya sebelum setiap perintah",
        ["perm.screen"] = "Izinkan menangkap layar",
        ["perm.input"] = "Izinkan mengendalikan mouse dan keyboard",
        ["perm.inputapproval"] = "Tanya sebelum setiap tindakan input",
        ["perm.skillscripts"] = "Izinkan menjalankan skrip bawaan skill",
        ["perm.skillscripts.approval"] = "Tanya sebelum setiap skrip",
        ["perm.skillscripts.hint"] = "Skill bisa membawa skrip. Menjalankannya berarti menjalankan kode dari repositori dengan hak akses penuh Anda, jadi sakelarnya terpisah dari shell.",
        ["perm.mcp"] = "Izinkan server MCP",
        ["perm.mcp.hint"] = "Server MCP adalah program yang dijalankan AutoWork dengan hak akses penuh Anda. PathGuard tidak bisa melihat ke dalamnya. Biarkan mati kecuali Anda memang membutuhkannya.",
        ["perm.network"] = "Izinkan akses jaringan",
        ["perm.searchkey"] = "Kunci API Tavily untuk pencarian web",
        ["perm.searchkeyhint"] = "Opsional. Tanpa kunci, pencarian tetap jalan lewat DuckDuckGo dan Wikipedia. Kunci disimpan terenkripsi, tidak pernah di config.json.",
        ["perm.confirm"] = "Tanya sebelum menulis, menghapus, atau menjalankan apa pun",

        ["agent.maxsteps"] = "Maksimum langkah per sesi",
        ["agent.subagents"] = "Bagi pekerjaan independen ke sub-agen paralel",
        ["agent.parallel"] = "Maksimum sub-agen paralel",
        ["agent.verify"] = "Periksa hasil kerja sendiri sebelum menyatakan selesai",
        ["agent.compact"] = "Ringkas konteks lama otomatis saat jendela hampir penuh",
        ["agent.threshold"] = "Ringkas saat terisi sebanyak ini",
        ["rules.title"] = "JAWABAN TETAP",
        ["rules.subtitle"] = "Jawab sekali, bukan setiap kali. Aturan ini menentukan apa yang ditanyakan kepada Anda — bukan memperluas jangkauan AutoWork, karena setiap tindakan tetap melewati folder yang Anda izinkan.",
        ["rules.none"] = "Belum ada aturan. Setiap tindakan akan ditanyakan.",
        ["rules.add"] = "Tambah aturan",
        ["rules.never"] = "Jangan pernah izinkan",
        ["rules.always"] = "Selalu izinkan",
        ["rules.anykind"] = "Semua tindakan",
        ["rules.path"] = "Folder yang berlaku",
        ["rules.browse"] = "Pilih…",

        ["models.pricing"] = "HARGA PER JUTA TOKEN",
        ["models.price.in"] = "Input",
        ["models.price.out"] = "Output",
        ["models.pricing.hint"] = "Opsional. Salin dari halaman harga penyedia Anda, lalu setiap run melaporkan biayanya. Dikosongkan berarti hanya token yang dilaporkan.",

        ["agent.localembed"] = "Cari pengetahuan tanpa keluar dari komputer ini",
        ["agent.localembed.hint"] = "Mengindeks catatan Anda di sini, bukan mengirimkannya ke model embedding. Ia mengenali bentukan kata dan tahan terhadap salah ketik, tetapi tidak tahu bahwa \"tagihan\" dan \"faktur\" bermakna sama — model daring lebih baik soal makna.",
        ["agent.streaming"] = "Tampilkan jawaban sambil ditulis",
        ["agent.history"] = "Simpan catatan setiap run",
        ["agent.retention"] = "Simpan run selama (hari)",

        ["appearance.theme"] = "Tema",
        ["appearance.theme.system"] = "Ikuti sistem",
        ["appearance.theme.light"] = "Terang",
        ["appearance.theme.dark"] = "Gelap",
        ["appearance.language"] = "Bahasa",
        ["appearance.language.system"] = "Ikuti sistem",
        ["appearance.motion"] = "Kurangi animasi",

        ["about.version"] = "Versi",
        ["about.datafolder"] = "Folder data",
        ["about.open"] = "Buka",

        ["common.save"] = "Simpan",
        ["common.cancel"] = "Batal",
        ["common.close"] = "Tutup",
        ["common.saved"] = "Tersimpan.",
        ["common.testing"] = "Menguji…",
    };
}
