# OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
"""Turns the notebooks into a compiled test, so their C# cannot rot.

A notebook is JSON, so nothing checks that its code still compiles when an API is renamed. This
lifts every code cell into a test method and hands it to the C# compiler. The docs needed exactly
this check and it found sixteen wrong API names, so the notebooks get it too.

One file per notebook rather than one merged file: merging them makes `TextAlignment` ambiguous
between PdfNet.Content and PowerPointNet.Shapes, which is a collision no notebook actually has.

    python tools/gen_notebook_tests.py
"""

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "tests", "OfficeNet.Docs.Tests", "Notebooks")

HEADER = """// OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
//
// GENERATED by tools/gen_notebook_tests.py from notebooks/{notebook}. Do not edit by hand — edit
// the notebook and regenerate, or the two drift apart and this file stops meaning anything.

{usings}
using Xunit;

namespace OfficeNet.Docs.Tests;

/// <summary>Every code cell in <c>notebooks/{notebook}</c>, compiled and run.</summary>
/// <remarks>
/// The kernel helpers are stubbed: <c>display</c> and <c>HTML</c> come from .NET Interactive and do
/// not exist here, so they become no-ops with the same signatures — enough to prove the surrounding
/// code compiles and runs. Rendering itself is covered by OfficeNet.Rendering.Tests.
/// </remarks>
public class {cls} : IDisposable
{{
    private readonly string _directory = System.IO.Path.Combine(
        System.IO.Path.GetTempPath(), "officenet-nb-" + Guid.NewGuid().ToString("N")[..8]);

    public {cls}() => Directory.CreateDirectory(_directory);

    public void Dispose()
    {{
        GC.SuppressFinalize(this);

        try
        {{
            Directory.Delete(_directory, recursive: true);
        }}
        catch (IOException)
        {{
            // A handle left open by a failing cell must not replace its failure with this one.
        }}
    }}

    private static object HTML(string markup) => markup;

    private static void display(object value) => _ = value;
"""

FOOTER = "}\n"


def code_cells(path):
    notebook = json.load(open(path, encoding="utf-8"))

    for cell in notebook["cells"]:
        if cell["cell_type"] == "code":
            yield "".join(cell["source"])


def convert(path):
    """Returns (usings, body) for one notebook."""
    usings = set()
    body = []

    for source in code_cells(path):
        kept = []

        for line in source.splitlines():
            stripped = line.strip()

            # #r and #! are kernel directives; the test project has real project references.
            if stripped.startswith("#r ") or stripped.startswith("#!"):
                continue

            if stripped.startswith("using ") and stripped.endswith(";") and "=" not in stripped:
                # Microsoft.DotNet.Interactive.* exists only inside the kernel.
                if not stripped.startswith("using Microsoft.DotNet.Interactive"):
                    usings.add(stripped)

                continue

            kept.append(line)

        # A cell's trailing bare expression is what the kernel displays as that cell's result. As
        # C# it is not a statement, so it becomes a discard — the point is that it still type-checks.
        for i in range(len(kept) - 1, -1, -1):
            stripped = kept[i].strip()

            if not stripped or stripped.startswith("//"):
                continue

            if not stripped.endswith((";", "{", "}")):
                kept[i] = "_ = " + stripped + ";"

            break

        for line in kept:
            body.append("        " + line if line.strip() else "")

        body.append("")

    text = "\n".join(body)

    # The notebooks make their own scratch directory; here the test fixture owns and cleans one.
    text = text.replace(
        'var work = Path.Combine(Path.GetTempPath(), "officenet-notebook");',
        "var work = _directory;")
    text = text.replace("Directory.CreateDirectory(work);\n", "")

    return usings, text


def main():
    if os.path.isdir(OUT_DIR):
        for stale in glob.glob(os.path.join(OUT_DIR, "*.cs")):
            os.remove(stale)

    os.makedirs(OUT_DIR, exist_ok=True)
    written = 0

    for path in sorted(glob.glob(os.path.join(ROOT, "notebooks", "*.ipynb"))):
        name = os.path.splitext(os.path.basename(path))[0]
        cls = "Notebook" + re.sub(r"[^A-Za-z0-9]", "", name)

        usings, body = convert(path)

        header = HEADER.format(
            usings="\n".join(sorted(usings)),
            cls=cls,
            notebook=os.path.basename(path))

        method = "\n    [Fact]\n    public void RunsEveryCell()\n    {\n" + body + "\n    }\n"

        with open(os.path.join(OUT_DIR, cls + ".cs"), "w", encoding="utf-8") as handle:
            handle.write(header)
            handle.write(method)
            handle.write(FOOTER)

        written += 1
        print(f"  {cls}.cs")

    print(f"Wrote {written} notebook tests to {OUT_DIR}")


if __name__ == "__main__":
    main()
