<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OfficeNet.Samples.Etl</RootNamespace>
    <AssemblyName>etlpipeline</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OfficeNet\OfficeNet.csproj" />
  </ItemGroup>

</Project>
