// OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
//
// GENERATED by tools/gen_notebook_tests.py from notebooks/PowerPointNet.ipynb. Do not edit by hand — edit
// the notebook and regenerate, or the two drift apart and this file stops meaning anything.

using OfficeNet.Core.Charts;
using OfficeNet.Core.Drawing;
using OfficeNet.Core;
using OfficeNet.Rendering;
using PowerPointNet.Charts;
using PowerPointNet.Html;
using PowerPointNet.Shapes;
using PowerPointNet;
using Xunit;

namespace OfficeNet.Docs.Tests;

/// <summary>Every code cell in <c>notebooks/PowerPointNet.ipynb</c>, compiled and run.</summary>
/// <remarks>
/// The kernel helpers are stubbed: <c>display</c> and <c>HTML</c> come from .NET Interactive and do
/// not exist here, so they become no-ops with the same signatures — enough to prove the surrounding
/// code compiles and runs. Rendering itself is covered by OfficeNet.Rendering.Tests.
/// </remarks>
public class NotebookPowerPointNet : IDisposable
{
    private readonly string _directory = System.IO.Path.Combine(
        System.IO.Path.GetTempPath(), "officenet-nb-" + Guid.NewGuid().ToString("N")[..8]);

    public NotebookPowerPointNet() => Directory.CreateDirectory(_directory);

    public void Dispose()
    {
        GC.SuppressFinalize(this);

        try
        {
            Directory.Delete(_directory, recursive: true);
        }
        catch (IOException)
        {
            // A handle left open by a failing cell must not replace its failure with this one.
        }
    }

    private static object HTML(string markup) => markup;

    private static void display(object value) => _ = value;

    [Fact]
    public void RunsEveryCell()
    {
        // Build first:  dotnet build OfficeNet.sln -c Release


        // Published instead? Swap the lines above for:
        //   #r "nuget: Gravicode.OfficeNet, *"


        // Renders a document and shows the first page inline, so a cell's effect is visible rather than
        // described. Base64 in an <img> because the notebook has nowhere to serve a file from.
        void Show(string path, int width = 520)
        {
            var png = DocumentRenderer.RenderThumbnail(path, width);
            var data = Convert.ToBase64String(png);

            display(HTML($"<img src='data:image/png;base64,{data}' style='border:1px solid #ddd' />"));
        }

        var work = _directory;
                string At(string name) => Path.Combine(work, name);

        Console.WriteLine($"Berkas ditulis ke / files written to: {work}");


        var deck = Presentation.Create();
        deck.Master!.SetThemeColor("accent1", OfficeColor.FromRgb(0x1F, 0x38, 0x64));

        deck.AddTitleSlide("OfficeNet", "Word, Excel, PowerPoint, dan PDF untuk .NET 10");

        deck.AddBulletSlide("Komponen", [
            "WordNet — python-docx",
            "ExcelNet — openpyxl + pandas",
            "PowerPointNet — python-pptx + PptxGenJS",
            "PdfNet — PyPDF2",
        ]);

        _ = $"{deck.SlideCount} slide, {deck.SlideWidth.Inches:0.###} x {deck.SlideHeight.Inches:0.###} inci";

        var slide = deck.AddSlide(2);
        slide.SetTitle("Pendapatan per Wilayah");

        slide.AddChart(new ChartData
        {
            Type = ChartType.Column,
            Categories = ["Jakarta", "Bandung", "Surabaya", "Medan"],
            Series =
            [
                new ChartSeries("2025", [1120, 860, 740, 410]),
                new ChartSeries("2026", [1480, 1150, 905, 520]),
            ],
            ValueAxisTitle = "Juta Rupiah",
            ValueFormat = "#,##0",
            ShowDataLabels = true,
            Legend = LegendPosition.Bottom,
        });

        deck.Save(At("deck.pptx"));
        Show(At("deck.pptx"), 640);

        var chart = slide.Charts.First();
        var data = chart.GetData();

        Console.WriteLine($"Tipe      : {data.Type}");
        Console.WriteLine($"Kategori  : {string.Join(", ", data.Categories)}");

        foreach (var series in data.Series)
            Console.WriteLine($"  {series.Name}: {string.Join(", ", series.Values)}");

        // Ubah tipenya tanpa menyusun ulang datanya.
        chart.SetData(data with { Type = ChartType.Bar });
        _ = chart.GetData().Type;

        var canvas = deck.AddSlide(3);   // Blank

        canvas.AddShape(ShapeGeometry.RoundedRectangle,
                Units.Inches(1), Units.Inches(1.4), Units.Inches(3.4), Units.Inches(1.6))
            .WithGradientFill(
                OfficeColor.FromRgb(0x1F, 0x38, 0x64),
                OfficeColor.FromRgb(0x63, 0x8E, 0xC6),
                GradientDirection.DiagonalDown)
            .WithShadow(blur: Units.Pt(10));

        canvas.AddShape(ShapeGeometry.Ellipse,
                Units.Inches(5.2), Units.Inches(1.4), Units.Inches(2.2), Units.Inches(2.2))
            .WithFill(OfficeColor.FromRgb(0xE8, 0x71, 0x22))
            .WithOutline(OfficeColor.White, Units.Pt(3));

        deck.Save(At("deck.pptx"));
        Show(At("deck.pptx"), 640);


        var html = @"
        <h1>Tinjauan Kuartal</h1>
        <p>Disusun oleh <strong>Gravicode Studios</strong>, dipimpin oleh <em>Kang Fadhil</em>.</p>
        <h2>Sorotan</h2>
        <ul>
          <li>Pendapatan naik <strong>32%</strong>
            <ul><li>Jakarta memimpin pertumbuhan</li></ul>
          </li>
          <li>Biaya operasional turun 4%</li>
        </ul>
        <h2>Ringkasan Angka</h2>
        <table>
          <tr><th>Wilayah</th><th>2025</th><th>2026</th></tr>
          <tr><td>Jakarta</td><td>1.120</td><td>1.480</td></tr>
          <tr><td>Bandung</td><td>860</td><td>1.150</td></tr>
        </table>";

        using (var fromHtml = HtmlToSlides.CreatePresentation(html, new HtmlSlideOptions
        {
            TitleSlide = "Dari HTML ke PowerPoint",
            SubtitleSlide = "Satu panggilan, tanpa penyuntingan manual",
        }))
        {
            Console.WriteLine($"{fromHtml.SlideCount} slide dihasilkan dari HTML");
            fromHtml.Save(At("html.pptx"));
        }

        Show(At("html.pptx"), 640);

        deck.SaveAsPdf(At("deck.pdf"));
        Show(At("deck.pdf"), 640);

        deck.Dispose();

    }
}
