// OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
//
// GENERATED by tools/gen_notebook_tests.py from notebooks/WordNet.ipynb. Do not edit by hand — edit
// the notebook and regenerate, or the two drift apart and this file stops meaning anything.

using OfficeNet.Core.Drawing;
using OfficeNet.Core;
using OfficeNet.Rendering;
using WordNet.Styles;
using WordNet;
using Xunit;

namespace OfficeNet.Docs.Tests;

/// <summary>Every code cell in <c>notebooks/WordNet.ipynb</c>, compiled and run.</summary>
/// <remarks>
/// The kernel helpers are stubbed: <c>display</c> and <c>HTML</c> come from .NET Interactive and do
/// not exist here, so they become no-ops with the same signatures — enough to prove the surrounding
/// code compiles and runs. Rendering itself is covered by OfficeNet.Rendering.Tests.
/// </remarks>
public class NotebookWordNet : IDisposable
{
    private readonly string _directory = System.IO.Path.Combine(
        System.IO.Path.GetTempPath(), "officenet-nb-" + Guid.NewGuid().ToString("N")[..8]);

    public NotebookWordNet() => Directory.CreateDirectory(_directory);

    public void Dispose()
    {
        GC.SuppressFinalize(this);

        try
        {
            Directory.Delete(_directory, recursive: true);
        }
        catch (IOException)
        {
            // A handle left open by a failing cell must not replace its failure with this one.
        }
    }

    private static object HTML(string markup) => markup;

    private static void display(object value) => _ = value;

    [Fact]
    public void RunsEveryCell()
    {
        // Build first:  dotnet build OfficeNet.sln -c Release


        // Published instead? Swap the lines above for:
        //   #r "nuget: Gravicode.OfficeNet, *"


        // Renders a document and shows the first page inline, so a cell's effect is visible rather than
        // described. Base64 in an <img> because the notebook has nowhere to serve a file from.
        void Show(string path, int width = 520)
        {
            var png = DocumentRenderer.RenderThumbnail(path, width);
            var data = Convert.ToBase64String(png);

            display(HTML($"<img src='data:image/png;base64,{data}' style='border:1px solid #ddd' />"));
        }

        var work = _directory;
                string At(string name) => Path.Combine(work, name);

        Console.WriteLine($"Berkas ditulis ke / files written to: {work}");


        var document = WordDocument.Create();

        var paragraph = document.AddParagraph();
        paragraph.Alignment = ParagraphAlignment.Justify;
        paragraph.AddRun("Pendapatan tumbuh ");
        paragraph.AddRun("32%", bold: true);
        paragraph.AddRun(" dibanding tahun sebelumnya, ditopang permintaan yang kuat di Jakarta.");

        var emphasis = document.AddParagraph().AddRun("Miring, bergaris bawah, berwarna.");
        emphasis.Format.Italic = true;
        emphasis.Format.Underline = UnderlineStyle.Single;
        emphasis.Format.Color = OfficeColor.FromRgb(0x1F, 0x38, 0x64);
        emphasis.Format.FontSize = Units.Pt(13);

        _ = document.ExtractText();

        document.AddHeading("Komponen", 1);

        document.AddList([
            "WordNet — python-docx",
            "ExcelNet — openpyxl + pandas",
            "PowerPointNet — python-pptx",
            "PdfNet — PyPDF2",
        ]);

        document.AddHeading("Langkah", 1);
        document.AddList(["Pasang paket", "Tulis kode", "Simpan"], numbered: true);

        var style = document.Styles.GetOrAdd("Catatan", "Catatan", StyleType.Paragraph, basedOn: "Normal");
        style.RunFormat.FontSize = Units.Pt(9);
        style.RunFormat.Italic = true;

        document.AddParagraph("Angka bersifat ilustratif.", "Catatan");

        _ = document.Styles.All.Count();

        document.AddHeading("Pendapatan per Wilayah", 1);

        var table = document.AddTable(new[]
        {
            new[] { "Wilayah", "2025", "2026", "Pertumbuhan" },
            new[] { "Jakarta", "1.120", "1.480", "+32%" },
            new[] { "Bandung", "860", "1.150", "+34%" },
            new[] { "Surabaya", "740", "905", "+22%" },
        });

        table.Rows[0].SetShading(OfficeColor.FromRgb(0x1F, 0x38, 0x64));

        foreach (var cell in table.Rows[0].Cells)
            foreach (var run in cell.Paragraphs.SelectMany(p => p.Runs))
                run.Format.Color = OfficeColor.White;

        _ = $"{table.Count} baris x {table.ColumnCount} kolom";

        var section = document.Section;
        section.SetPageSize("A4");
        section.SetMargins(Units.Cm(2.2));

        section.GetHeader().AddParagraph("Gravicode Studios").Alignment = ParagraphAlignment.Right;

        var footer = section.GetFooter().AddParagraph();
        footer.Alignment = ParagraphAlignment.Center;
        footer.AddRun("Halaman ");
        footer.AddPageNumber();
        footer.AddRun(" dari ");
        footer.AddPageCount();

        document.Properties.Title = "Laporan Tahunan";
        document.Properties.Creator = "Gravicode Studios";

        document.Save(At("wordnet.docx"));
        Show(At("wordnet.docx"));

        using var letter = WordDocument.Create();
        letter.AddParagraph("Kepada {{nama}} di {{kota}},");
        letter.AddParagraph("Terima kasih atas pesanan Anda pada tahun 2025.");

        letter.MailMerge(new Dictionary<string, string>
        {
            ["nama"] = "Budi Santoso",
            ["kota"] = "Bandung",
        });

        letter.ReplaceTextAcrossRuns("2025", "2026");

        _ = letter.ExtractText();

        document.SaveAsPdf(At("wordnet.pdf"), new WordNet.Export.PdfExportOptions
        {
            Watermark = "DRAF",
            WatermarkOpacity = 0.10,
        });

        Show(At("wordnet.pdf"));

        document.Dispose();

    }
}
