// OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
//
// GENERATED by tools/gen_notebook_tests.py from notebooks/ExcelNet.ipynb. Do not edit by hand — edit
// the notebook and regenerate, or the two drift apart and this file stops meaning anything.

using ExcelNet.Io;
using ExcelNet.Styles;
using ExcelNet;
using OfficeNet.Core.Drawing;
using OfficeNet.Rendering;
using Xunit;

namespace OfficeNet.Docs.Tests;

/// <summary>Every code cell in <c>notebooks/ExcelNet.ipynb</c>, compiled and run.</summary>
/// <remarks>
/// The kernel helpers are stubbed: <c>display</c> and <c>HTML</c> come from .NET Interactive and do
/// not exist here, so they become no-ops with the same signatures — enough to prove the surrounding
/// code compiles and runs. Rendering itself is covered by OfficeNet.Rendering.Tests.
/// </remarks>
public class NotebookExcelNet : IDisposable
{
    private readonly string _directory = System.IO.Path.Combine(
        System.IO.Path.GetTempPath(), "officenet-nb-" + Guid.NewGuid().ToString("N")[..8]);

    public NotebookExcelNet() => Directory.CreateDirectory(_directory);

    public void Dispose()
    {
        GC.SuppressFinalize(this);

        try
        {
            Directory.Delete(_directory, recursive: true);
        }
        catch (IOException)
        {
            // A handle left open by a failing cell must not replace its failure with this one.
        }
    }

    private static object HTML(string markup) => markup;

    private static void display(object value) => _ = value;

    [Fact]
    public void RunsEveryCell()
    {
        // Build first:  dotnet build OfficeNet.sln -c Release


        // Published instead? Swap the lines above for:
        //   #r "nuget: Gravicode.OfficeNet, *"


        // Renders a document and shows the first page inline, so a cell's effect is visible rather than
        // described. Base64 in an <img> because the notebook has nowhere to serve a file from.
        void Show(string path, int width = 520)
        {
            var png = DocumentRenderer.RenderThumbnail(path, width);
            var data = Convert.ToBase64String(png);

            display(HTML($"<img src='data:image/png;base64,{data}' style='border:1px solid #ddd' />"));
        }

        var work = _directory;
                string At(string name) => Path.Combine(work, name);

        Console.WriteLine($"Berkas ditulis ke / files written to: {work}");


        var workbook = Workbook.Create("Penjualan");
        var sheet = workbook["Penjualan"];

        sheet.WriteHeader("A1", ["Tanggal", "Produk", "Wilayah", "Qty", "Harga", "Total"]);

        string[] products = ["WordNet", "ExcelNet", "PowerPointNet", "PdfNet"];
        string[] regions  = ["Jakarta", "Bandung", "Surabaya"];
        var random = new Random(7);

        for (var i = 0; i < 12; i++)
        {
            var row = i + 1;
            sheet[row, 0].Set(new DateTime(2026, 1, 5).AddDays(i * 4));
            sheet[row, 1].Set(products[i % products.Length]);
            sheet[row, 2].Set(regions[i % regions.Length]);
            sheet[row, 3].Set(random.Next(4, 40));
            sheet[row, 4].Set(random.Next(60, 280) * 1000.0).WithNumberFormat(NumberFormats.Rupiah);
            sheet[row, 5].SetFormula($"D{row + 1}*E{row + 1}").WithNumberFormat(NumberFormats.Rupiah);
        }

        _ = $"{sheet.RowCount} baris, {sheet.CellCount} sel terpakai";

        sheet["E14"].Set("TOTAL").Bold();
        sheet["F14"].SetFormula("SUM(F2:F13)").WithStyle(
            CellStyle.Default.Bold()
                .WithNumberFormat(NumberFormats.Rupiah)
                .WithBackground(OfficeColor.FromRgb(0xFF, 0xF2, 0xCC)));

        sheet["E15"].Set("RATA-RATA").Bold();
        sheet["F15"].SetFormula("AVERAGE(F2:F13)").WithNumberFormat(NumberFormats.Rupiah);

        Console.WriteLine($"Sebelum Recalculate: {sheet["F14"].Number:N0}");

        workbook.Recalculate();

        Console.WriteLine($"Sesudah  Recalculate: {sheet["F14"].Number:N0}");

        using var quirks = Workbook.Create("Quirks");
        var q = quirks["Quirks"];

        q["A1"].SetFormula("ROUND(2.5,0)");    // 3, bukan 2 (bukan pembulatan bankir)
        q["A2"].SetFormula("MOD(-3,2)");       // 1, mengikuti tanda pembagi
        q["A3"].SetFormula("-2^2");            // 4, minus uner mengikat lebih kuat
        q["A4"].SetFormula("1/0");             // #DIV/0! sebagai nilai, bukan exception
        q["A5"].SetFormula("IFERROR(A4,\"aman\")");

        quirks.Recalculate();

        foreach (var address in new[] { "A1", "A2", "A3", "A4", "A5" })
            Console.WriteLine($"{address}  {q[address].Formula,-22} = {q[address].Text}");

        var header = CellStyle.Default
            .Bold()
            .WithColor(OfficeColor.White)
            .WithBackground(OfficeColor.FromRgb(0x1F, 0x38, 0x64))
            .WithAlignment(HorizontalAlignment.Center);

        sheet.Range("A1:F1").ApplyStyle(header);

        sheet.AddColorScale("D2:D13",
            OfficeColor.FromRgb(0xF8, 0x69, 0x6B),
            OfficeColor.FromRgb(0x63, 0xBE, 0x7B));

        sheet.Frozen = new FreezePanes(Rows: 1, Columns: 0);
        sheet.AutoFitColumns();
        sheet.TabColor = OfficeColor.FromRgb(0x1F, 0x38, 0x64);

        workbook.Save(At("excelnet.xlsx"));
        Show(At("excelnet.xlsx"), 700);


        var csv = CsvIo.ExportText(sheet, CsvOptions.Indonesian);
        Console.WriteLine(string.Join("\n", csv.Split('\n').Take(4)));

        Console.WriteLine();
        var json = JsonIo.ExportText(sheet);
        Console.WriteLine(json[..Math.Min(260, json.Length)] + "…");

        workbook.SaveAsPdf(At("excelnet.pdf"), new ExcelPdfOptions
        {
            ShowGridLines = true,
            RepeatHeaderRow = true,
        });

        Show(At("excelnet.pdf"), 700);

        workbook.Dispose();

    }
}
