// OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
//
// GENERATED by tools/gen_notebook_tests.py from notebooks/00-Quickstart.ipynb. Do not edit by hand — edit
// the notebook and regenerate, or the two drift apart and this file stops meaning anything.

using ExcelNet.Styles;
using ExcelNet;
using OfficeNet.Core.Charts;
using OfficeNet.Core.Drawing;
using OfficeNet.Core;
using OfficeNet.Rendering;
using OfficeNet;
using PowerPointNet.Charts;
using PowerPointNet;
using WordNet;
using Xunit;

namespace OfficeNet.Docs.Tests;

/// <summary>Every code cell in <c>notebooks/00-Quickstart.ipynb</c>, compiled and run.</summary>
/// <remarks>
/// The kernel helpers are stubbed: <c>display</c> and <c>HTML</c> come from .NET Interactive and do
/// not exist here, so they become no-ops with the same signatures — enough to prove the surrounding
/// code compiles and runs. Rendering itself is covered by OfficeNet.Rendering.Tests.
/// </remarks>
public class Notebook00Quickstart : IDisposable
{
    private readonly string _directory = System.IO.Path.Combine(
        System.IO.Path.GetTempPath(), "officenet-nb-" + Guid.NewGuid().ToString("N")[..8]);

    public Notebook00Quickstart() => Directory.CreateDirectory(_directory);

    public void Dispose()
    {
        GC.SuppressFinalize(this);

        try
        {
            Directory.Delete(_directory, recursive: true);
        }
        catch (IOException)
        {
            // A handle left open by a failing cell must not replace its failure with this one.
        }
    }

    private static object HTML(string markup) => markup;

    private static void display(object value) => _ = value;

    [Fact]
    public void RunsEveryCell()
    {
        // Build first:  dotnet build OfficeNet.sln -c Release


        // Published instead? Swap the lines above for:
        //   #r "nuget: Gravicode.OfficeNet, *"


        // Renders a document and shows the first page inline, so a cell's effect is visible rather than
        // described. Base64 in an <img> because the notebook has nowhere to serve a file from.
        void Show(string path, int width = 520)
        {
            var png = DocumentRenderer.RenderThumbnail(path, width);
            var data = Convert.ToBase64String(png);

            display(HTML($"<img src='data:image/png;base64,{data}' style='border:1px solid #ddd' />"));
        }

        var work = _directory;
                string At(string name) => Path.Combine(work, name);

        Console.WriteLine($"Berkas ditulis ke / files written to: {work}");


        using (var document = WordDocument.Create())
        {
            document.AddHeading("Laporan Tahunan", 0);
            document.AddParagraph("Dibuat oleh Gravicode Studios.", "Subtitle");

            document.AddHeading("Pendapatan", 1);

            var table = document.AddTable(new[]
            {
                new[] { "Wilayah", "2025", "2026" },
                new[] { "Jakarta", "1.120", "1.480" },
                new[] { "Bandung", "860", "1.150" },
            });

            table.Rows[0].SetShading(OfficeColor.FromRgb(0x1F, 0x38, 0x64));

            foreach (var cell in table.Rows[0].Cells)
                foreach (var run in cell.Paragraphs.SelectMany(p => p.Runs))
                    run.Format.Color = OfficeColor.White;

            document.Save(At("laporan.docx"));
        }

        Show(At("laporan.docx"));


        using (var workbook = Workbook.Create("Penjualan"))
        {
            var sheet = workbook["Penjualan"];
            sheet.WriteHeader("A1", ["Produk", "Qty", "Harga", "Total"]);

            string[] products = ["WordNet", "ExcelNet", "PowerPointNet", "PdfNet"];

            for (var i = 0; i < products.Length; i++)
            {
                var row = i + 1;
                sheet[row, 0].Set(products[i]);
                sheet[row, 1].Set((i + 2) * 7);
                sheet[row, 2].Set(150_000.0).WithNumberFormat(NumberFormats.Rupiah);
                sheet[row, 3].SetFormula($"B{row + 1}*C{row + 1}").WithNumberFormat(NumberFormats.Rupiah);
            }

            sheet["C6"].Set("TOTAL").Bold();
            sheet["D6"].SetFormula("SUM(D2:D5)").WithNumberFormat(NumberFormats.Rupiah);

            sheet.AutoFitColumns();
            workbook.Recalculate();

            Console.WriteLine($"Total = {sheet["D6"].Number:N0}");
            workbook.Save(At("penjualan.xlsx"));
        }

        Show(At("penjualan.xlsx"), 640);


        using (var deck = Presentation.Create())
        {
            deck.AddTitleSlide("OfficeNet", "Empat format, satu API");

            // Layout 2 is "Title Only": the title sits at the top and the rest of the slide is free.
            var slide = deck.AddSlide(2);
            slide.SetTitle("Pendapatan per Wilayah");

            slide.AddChart(new ChartData
            {
                Type = ChartType.Column,
                Categories = ["Jakarta", "Bandung", "Surabaya"],
                Series = [new ChartSeries("2026", [1480, 1150, 905])],
                ValueFormat = "#,##0",
                ShowDataLabels = true,
            });

            deck.Save(At("deck.pptx"));
        }

        Show(At("deck.pptx"), 640);


        foreach (var name in new[] { "laporan.docx", "penjualan.xlsx", "deck.pptx" })
        {
            var pdf = Office.ConvertToPdf(At(name));
            Console.WriteLine($"{name,-20} -> {Path.GetFileName(pdf)}  ({new FileInfo(pdf).Length / 1024.0:0.0} KB)");
        }

        Console.WriteLine();
        var text = Office.ExtractText(At("laporan.docx"));
        Console.WriteLine(text[..Math.Min(120, text.Length)] + "…");

    }
}
