// OfficeNet - Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.
//
// GENERATED by tools/gen_notebook_tests.py from notebooks/PdfNet.ipynb. Do not edit by hand — edit
// the notebook and regenerate, or the two drift apart and this file stops meaning anything.

using OfficeNet.Core.Drawing;
using OfficeNet.Rendering;
using PdfNet.Annotations;
using PdfNet.Content;
using PdfNet.Document;
using PdfNet.Security;
using Xunit;

namespace OfficeNet.Docs.Tests;

/// <summary>Every code cell in <c>notebooks/PdfNet.ipynb</c>, compiled and run.</summary>
/// <remarks>
/// The kernel helpers are stubbed: <c>display</c> and <c>HTML</c> come from .NET Interactive and do
/// not exist here, so they become no-ops with the same signatures — enough to prove the surrounding
/// code compiles and runs. Rendering itself is covered by OfficeNet.Rendering.Tests.
/// </remarks>
public class NotebookPdfNet : IDisposable
{
    private readonly string _directory = System.IO.Path.Combine(
        System.IO.Path.GetTempPath(), "officenet-nb-" + Guid.NewGuid().ToString("N")[..8]);

    public NotebookPdfNet() => Directory.CreateDirectory(_directory);

    public void Dispose()
    {
        GC.SuppressFinalize(this);

        try
        {
            Directory.Delete(_directory, recursive: true);
        }
        catch (IOException)
        {
            // A handle left open by a failing cell must not replace its failure with this one.
        }
    }

    private static object HTML(string markup) => markup;

    private static void display(object value) => _ = value;

    [Fact]
    public void RunsEveryCell()
    {
        // Build first:  dotnet build OfficeNet.sln -c Release


        // Published instead? Swap the lines above for:
        //   #r "nuget: Gravicode.OfficeNet, *"


        // Renders a document and shows the first page inline, so a cell's effect is visible rather than
        // described. Base64 in an <img> because the notebook has nowhere to serve a file from.
        void Show(string path, int width = 520)
        {
            var png = DocumentRenderer.RenderThumbnail(path, width);
            var data = Convert.ToBase64String(png);

            display(HTML($"<img src='data:image/png;base64,{data}' style='border:1px solid #ddd' />"));
        }

        var work = _directory;
                string At(string name) => Path.Combine(work, name);

        Console.WriteLine($"Berkas ditulis ke / files written to: {work}");


        var document = PdfDocument.Create();
        var page = document.Pages.Add(PageSize.A4);

        using (var canvas = page.OpenCanvas())
        {
            canvas.TopDown = true;

            canvas.SetFillColor(OfficeColor.FromRgb(0x1F, 0x38, 0x64));
            canvas.Rectangle(0, 0, page.Width, 90).Fill();

            canvas.SetFont(StandardFont.HelveticaBold, 26);
            canvas.SetFillColor(OfficeColor.White);
            canvas.DrawText("Laporan Tahunan", 56, 56);

            canvas.SetFont(StandardFont.Helvetica, 11);
            canvas.SetFillColor(OfficeColor.Black);
            canvas.DrawText(
                "Pendapatan tumbuh 32% dibanding tahun sebelumnya, ditopang permintaan yang " +
                "kuat di Jakarta dan Bandung. Seluruh wilayah menutup tahun di atas target.",
                56, 140, page.Width - 112, TextAlignment.Justify);

            var y = 210.0;

            foreach (var (label, value) in new[] {
                ("Jakarta", 1480.0), ("Bandung", 1150.0), ("Surabaya", 905.0), ("Medan", 520.0) })
            {
                canvas.SetFillColor(OfficeColor.FromRgb(0x63, 0x8E, 0xC6));
                canvas.Rectangle(140, y, value / 4, 18).Fill();

                canvas.SetFillColor(OfficeColor.Black);
                canvas.SetFont(StandardFont.Helvetica, 10);
                canvas.DrawText(label, 56, y + 13);
                canvas.DrawText($"{value:N0}", 148 + value / 4, y + 13);

                y += 28;
            }
        }

        document.Info.Title = "Laporan Tahunan";
        document.Info.Author = "Gravicode Studios";
        document.Save(At("gambar.pdf"));

        Show(At("gambar.pdf"));

        using var reopened = PdfDocument.Open(At("gambar.pdf"));

        Console.WriteLine(reopened.ExtractText());
        Console.WriteLine(new string('-', 60));

        foreach (var fragment in reopened.Pages[0].ExtractTextFragments().Take(6))
            Console.WriteLine($"{fragment.Text,-28} @ ({fragment.X,6:0.#}, {fragment.Y,6:0.#})  {fragment.FontSize}pt");

        using var wordDocument = WordNet.WordDocument.Create();
        wordDocument.AddHeading("Lampiran", 1);
        wordDocument.AddParagraph("Halaman tambahan dari WordNet.");
        wordDocument.SaveAsPdf(At("lampiran.pdf"));

        using var a = PdfDocument.Open(At("gambar.pdf"));
        using var b = PdfDocument.Open(At("lampiran.pdf"));

        Console.WriteLine($"Sebelum: {a.Pages.Count} halaman");
        a.Merge(b);
        Console.WriteLine($"Sesudah: {a.Pages.Count} halaman");

        a.Save(At("gabungan.pdf"));

        var parts = PdfDocument.Open(At("gabungan.pdf")).Split();
        Console.WriteLine($"Dipisah menjadi {parts.Count} dokumen");
        foreach (var part in parts) part.Dispose();


        using var annotated = PdfDocument.Open(At("gambar.pdf"));
        var target = annotated.Pages[0];

        target.AddWatermark("DRAF", OfficeColor.Gray, 0.10);
        target.AddTextNote(500, 200, "Perlu ditinjau sebelum rilis.", "Kang Fadhil");
        target.AddHighlight([new PdfRectangle(56, 130, 300, 150)], OfficeColor.FromRgb(0xFF, 0xF0, 0x00));

        annotated.Save(At("anotasi.pdf"));

        Console.WriteLine($"{target.GetAnnotations().Count} anotasi");
        Show(At("anotasi.pdf"));

        using (var secret = PdfDocument.Open(At("gambar.pdf")))
        {
            secret.Encrypt(
                userPassword: "buka",
                ownerPassword: "pemilik",
                permissions: PdfPermissions.Print,
                cipher: PdfCipher.Aes256);

            secret.Save(At("terkunci.pdf"));
        }

        try
        {
            using var _ = PdfDocument.Open(At("terkunci.pdf"));
            Console.WriteLine("Terbuka tanpa kata sandi — tidak seharusnya!");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Tanpa kata sandi: {ex.GetType().Name}");
        }

        using var unlocked = PdfDocument.Open(At("terkunci.pdf"), "buka");
        Console.WriteLine($"Dengan kata sandi: {unlocked.Pages.Count} halaman, izin = {unlocked.Permissions}");

        document.Dispose();

    }
}
